name: pre-commit

on:
  pull_request:
  push:
    branches: [main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - uses: pre-commit/action@v3.0.0
        if: always()
      #TfLint
      - uses: terraform-linters/setup-tflint@v2
        name: Setup TFLint
        if: always()
        with:
          github_token: ${{ secrets.CI_GITHUB_TOKEN }}
      # Install plugins
      - name: Init TFLint
        run: tflint --init
        if: always()

      # Run tflint command in each directory recursively
      - name: Run TFLint
        run: tflint -f compact --recursive --minimum-failure-severity=error
        if: always()

      # Tfsec - Security scanner for your Terraform code
      - name: Run Tfsec
        uses: aquasecurity/tfsec-action@v1.0.0
        if: always()
